# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(max_length=100, verbose_name='Groupe de quatier , Cités')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier , Rue...')),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la boutique:')),
                ('email_boutique', models.CharField(max_length=100, verbose_name='E-mail')),
                ('numero_service', models.CharField(max_length=100, verbose_name='numéro service 1:')),
                ('second_num_service', models.CharField(max_length=100, null=True, verbose_name='numéro service 2:')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieMere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande_for_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=100)),
                ('lieu_de_livraison', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la commande')),
                ('vue', models.BooleanField(default=False)),
                ('Livre', models.BooleanField(default=False)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Localité')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Message_for_vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commander', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField(verbose_name='Prix du produit')),
                ('quantite', models.IntegerField(verbose_name='Quantite en stok')),
                ('description', models.TextField()),
                ('photo_img1', models.ImageField(upload_to='photos/')),
                ('photo_img2', models.ImageField(upload_to='photos/')),
                ('photo_img3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_img4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_img5', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_creat', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Région')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pays')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Userclient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.User')),
                ('signature', models.TextField(blank=True, null=True)),
            ],
            bases=('shop.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit'),
        ),
        migrations.AddField(
            model_name='localite',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Region'),
        ),
        migrations.AddField(
            model_name='commission',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Panier'),
        ),
        migrations.AddField(
            model_name='commande_for_shop',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Panier'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_mere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategorieMere'),
        ),
        migrations.AddField(
            model_name='address',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Localite'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique'),
        ),
        migrations.CreateModel(
            name='Uservendeur',
            fields=[
                ('userclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Userclient')),
                ('numero', models.CharField(max_length=100)),
            ],
            bases=('shop.userclient',),
        ),
        migrations.AddField(
            model_name='userclient',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Userclient'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Userclient'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Uservendeur'),
        ),
    ]
