# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveau_prix', models.FloatField(verbose_name='Nouveau prix')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Début de promo ')),
                ('duree', models.IntegerField(verbose_name='Durée ( en jours ) ')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
            ],
        ),
    ]
