# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promo_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='date_fin',
            field=models.DateTimeField(null=True, verbose_name='fin promo'),
        ),
    ]
