# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_promo_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='nom_abrj',
            field=models.CharField(max_length=100, null=True, verbose_name='Abréviation'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='type_de_vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CategorieMere'),
        ),
    ]
