# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_produit_prix_normal'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_normal',
            field=models.FloatField(default=0, null=True, verbose_name='Prix normal du produit'),
        ),
    ]
