# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180418_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_normal',
            field=models.FloatField(default=0, verbose_name='Prix normal du produit'),
        ),
    ]
